#!/usr/bin/env bash
# tells a story

input="/etc/passwd"
while IFS=: read -r USERNAME GROUP_ID $HOME_DIRECTORY COMMAND/SHELL USER ID PASSWORD 
do
	echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND/SHELL. $USER ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER ID INFO"
done < "$input" 
