#!/usr/bin/env bash
# Displays Best school using while and if

COUNTER=0
while [ $COUNTER -lt 11 ]
do
	if [ $COUNTER = 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	(( a++ )) || true  COUNTER+=1
done
